/*商城區資料重刷*/
CREATE DATABASE IF NOT EXISTS `CFA104G2`;

use CFA104G2;

DROP TABLE IF EXISTS `SHOP_HASHTAG_DETAILS`;
DROP TABLE IF EXISTS `SHOP_HASHTAG_PRODUCT`;
DROP TABLE IF EXISTS `SHOP_CARTLIST`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_COLLECTION`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_REPORT`;
DROP TABLE IF EXISTS `SHOP_ORDER_DETAILS`;
DROP TABLE IF EXISTS `SHOP_ORDER`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_PIC`;
DROP TABLE IF EXISTS `SHOP_PRODUCT`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_TYPE`;
-- DROP TABLE IF EXISTS `F_MEM`;
-- DROP TABLE IF EXISTS `MEM`;

-- 暫時建立用來做FK
-- CREATE TABLE `CFA104G2`.`MEM` (
-- `MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '一般會員編號',
-- PRIMARY KEY (`MEM_ID`));

--  暫時建立用來做FK
-- CREATE TABLE  `CFA104G2`.`F_MEM` (
-- `F_MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT'小農會員編號',
-- PRIMARY KEY (`F_MEM_ID`));

/*2-3.商品類別*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_TYPE` (
  `PROD_TYPE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品類別編號',
  `PROD_TYPE_NAME` VARCHAR(20) NOT NULL COMMENT '商品類別名稱',
  PRIMARY KEY (`PROD_TYPE_ID`))
COMMENT = '2-3.商品類別';

/*2-1.商城商品*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT` (
  `PROD_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品編號',
  `PROD_TYPE_ID` INT NOT NULL COMMENT '商品類別編號',
  `PROD_NAME` VARCHAR(40) NOT NULL COMMENT '商品名稱',
  `F_MEM_ID` INT NOT NULL COMMENT '小農會員編號',
  `PROD_STATUS` TINYINT NOT NULL COMMENT '商品狀態',
  `PROD_PRICE` INT NOT NULL COMMENT '商品價格',
  `PROD_QTY` INT NOT NULL COMMENT '商品數量',
  `PROD_INTRO` VARCHAR(800) NOT NULL COMMENT '商品介紹',
  `PROD_REG_DATE` DATETIME NOT NULL COMMENT '商品上架日期',
  PRIMARY KEY (`PROD_ID`),
  INDEX `F_MEM_ID_idx` (`F_MEM_ID` ASC) VISIBLE,
  INDEX `PROD_TYPE_ID_idx` (`PROD_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_PRODUCT_F_MEM_ID`
    FOREIGN KEY (`F_MEM_ID`)
    REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
   CONSTRAINT `FK_SHOP_PRODUCT_PROD_TYPE_ID`
	FOREIGN KEY (`PROD_TYPE_ID`)
	REFERENCES `CFA104G2`.`SHOP_PRODUCT_TYPE` (`PROD_TYPE_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '2-1商城商品';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT` 
DROP FOREIGN KEY `FK_SHOP_PRODUCT_F_MEM_ID`,
DROP FOREIGN KEY `FK_SHOP_PRODUCT_PROD_TYPE_ID`;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_F_MEM_ID`
  FOREIGN KEY (`F_MEM_ID`)
  REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`),
ADD CONSTRAINT `FK_SHOP_PRODUCT_PROD_TYPE_ID`
  FOREIGN KEY (`PROD_TYPE_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT_TYPE` (`PROD_TYPE_ID`);


/*2-2.商城商品照片 */
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_PIC` (
  `PROD_PIC_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品圖片編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `PROD_PIC` LONGBLOB NULL COMMENT '商品圖片',
  PRIMARY KEY (`PROD_PIC_ID`),
  INDEX `PROD_ID_idx` (`PROD_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_PRODUCT_PIC_PROD_ID`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '2-2.商城商品照片';


/*2-4.商城訂單*/
CREATE TABLE `CFA104G2`.`SHOP_ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商城訂單編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `ORDER_DATE` DATETIME NOT NULL COMMENT '訂單日期',
  `ORDER_SHIPMENT` TINYINT NOT NULL COMMENT '出貨方式',
  `ORDER_SHIP_FEE` INT NOT NULL COMMENT '運費',
  `ORDER_AMOUNT` DECIMAL NOT NULL COMMENT '總金額',
  `ORDER_PAYMENT` TINYINT NOT NULL COMMENT '付款方式',
  `RETURN_RULE` TINYINT NOT NULL COMMENT '退貨規範\n0:退款  1:退貨   2:需協商',
  `ORDER_MEMO` VARCHAR(20) NULL COMMENT '訂單備註',
  `ORDER_SHIP_DATE` DATETIME NOT NULL COMMENT '出貨日期',
  `ORDER_STATE` TINYINT NOT NULL COMMENT '訂單狀態\n0: 等待付款中  1: 已取消  2: 等待賣家確認中  3: 出貨準備中  4: 已出貨  5: 未取貨，退回賣家 ',
  PRIMARY KEY (`ORDER_ID`),
  INDEX `MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_ORDER_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '2-4.商城訂單';

ALTER TABLE `CFA104G2`.`SHOP_ORDER` 
DROP FOREIGN KEY `FK_SHOP_ORDER_MEM_ID`;
ALTER TABLE `CFA104G2`.`SHOP_ORDER` 
ADD CONSTRAINT `FK_SHOP_ORDER_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`);

/*2-5.商城訂單明細*/
CREATE TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` (
  `ORDER_ID` INT NOT NULL COMMENT '商城訂單編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `ORDER_QTY` INT NOT NULL COMMENT '購買數量',
  `ORDER_UNIT_PRICE` INT NOT NULL COMMENT '單價',
  `PROD_ID_STARS` INT NULL COMMENT '商品星數',
  `MEM_ID_STARS` INT NULL COMMENT '一般會員星數',
  PRIMARY KEY (`ORDER_ID`, `PROD_ID`))
COMMENT = '2-5.商城訂單明細';

ALTER TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` 
ADD INDEX `FK_SHOP_ORDER_DETAILS_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` 
ADD CONSTRAINT `FK_SHOP_ORDER_DETAILS_ORDER_ID`
  FOREIGN KEY (`ORDER_ID`)
  REFERENCES `CFA104G2`.`SHOP_ORDER` (`ORDER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_ORDER_DETAILS_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*2-6.商品檢舉單*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` (
  `PROD_REPORT_NO` INT NOT NULL AUTO_INCREMENT COMMENT '商品檢舉編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `REPORT_REASON` VARCHAR(800) NOT NULL COMMENT '檢舉事由',
  `REPORT_TIME` DATETIME NOT NULL COMMENT '檢舉日期',
  `REPORT_STATE` TINYINT NOT NULL COMMENT '檢舉狀態\n0: 未處理\n1: 檢舉通過\n2: 檢舉未通過',
  `REPORT_NOTE` VARCHAR(300) NULL COMMENT '檢舉備註',
  PRIMARY KEY (`PROD_REPORT_NO`))
COMMENT = '2-6.商品檢舉單';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` 
ADD INDEX `FK_SHOP_PRODUCT_REPORT_MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
ADD INDEX `FK_SHOP_PRODUCT_REPORT_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_REPORT_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_PRODUCT_REPORT_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*2-7.商品收藏列表*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` (
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `PROD_FAV_DATE` DATETIME NOT NULL COMMENT '加入收藏日期',
  PRIMARY KEY (`MEM_ID`, `PROD_ID`))
COMMENT = '2-7.商品收藏列表';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` 
ADD INDEX `FK_SHOP_PRODUCT_COLLECTION_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_COLLECTION_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_PRODUCT_COLLECTION_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*2-8.商城購物車列表*/
CREATE TABLE `CFA104G2`.`SHOP_CARTLIST` (
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `CARTLIST_QTY` INT NOT NULL COMMENT '購買數量',
  `CARTLIST_UNIT_PRICE` INT NOT NULL COMMENT '單價',
  PRIMARY KEY (`MEM_ID`,`PROD_ID`))
COMMENT = '2-8.商城購物車列表';

ALTER TABLE `CFA104G2`.`SHOP_CARTLIST` 
ADD INDEX `FK_SHOP_CARTLIST_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_CARTLIST` 
ADD CONSTRAINT `FK_SHOP_CARTLIST_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_CARTLIST_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/*2-9.商品主題標籤*/
CREATE TABLE `CFA104G2`.`SHOP_HASHTAG` (
  `HASH_NO` INT NOT NULL AUTO_INCREMENT COMMENT '商品主題標籤編號',
  `HASH_WORD` VARCHAR(45) NOT NULL COMMENT '商品主題關鍵字',
  PRIMARY KEY (`HASH_NO`))
COMMENT = '2-9.商品主題標籤';

/*2-10.商品主題標籤明細*/
CREATE TABLE `CFA104G2`.`SHOP_HASHTAG_DETAILS` (
  `HASHTAG_NO` INT NOT NULL COMMENT '商品主題標籤編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  PRIMARY KEY (`HASHTAG_NO`, `PROD_ID`),
  INDEX `PROD_ID_idx` (`PROD_ID` ASC) VISIBLE,
  CONSTRAINT `SHOP_HASHTAG_HASHTAG_NO`
    FOREIGN KEY (`HASHTAG_NO`)
    REFERENCES `CFA104G2`.`SHOP_HASHTAG` (`HASH_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SHOP_PRODUCT_PROD_ID`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '2-10.商品主題標籤明細';