/*會員小農區無法單獨重刷(影響到其他資料表區)*/
CREATE DATABASE IF NOT EXISTS CFA104G2;

use CFA104G2;

DROP TABLE IF EXISTS PRIVATE_MESSAGE;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS F_MEM;
DROP TABLE IF EXISTS MEM;

/*一般會員*/
/*77為M之十進位制*/
set auto_increment_offset=77000;
set auto_increment_increment=1;
CREATE TABLE `CFA104G2`.`MEM` (
  `MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '一般會員編號',
  `MEM_ACC` VARCHAR(40) NOT NULL COMMENT '帳號',
  `MEM_PWD` VARCHAR(20) NOT NULL COMMENT '密碼',
  `ACC_STATE` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '帳號狀態',
  `MEM_NAME` VARCHAR(20) NOT NULL COMMENT '姓名',
  `MEM_NICKNAME` VARCHAR(20) NOT NULL COMMENT '暱稱',
  `MEM_MOBILE` VARCHAR(10) NOT NULL COMMENT '手機',
  `MEM_TEL` VARCHAR(10) NULL COMMENT '市話',
  `MEM_ZIPCODE` INT NOT NULL COMMENT '郵遞區號',
  `MEM_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `MEM_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `MEM_ADDR` VARCHAR(40) NOT NULL COMMENT '地址',
  `REG_DATE` DATETIME NOT NULL COMMENT '加入時間',
  `MEM_PIC` LONGBLOB NULL COMMENT '會員頭貼',
  `RATING_SCORE_MK` INT NULL COMMENT '商城總分數',
  `RATING_COUNT_MK` INT NULL COMMENT '商城總評價數',
  `RATING_SCORE_TR` INT NULL COMMENT '旅遊總分數',
  `RATING_COUNT_TR` INT NULL COMMENT '旅遊總評價數',
  `REPORT_COUNT` TINYINT(2) NULL COMMENT '被檢舉計點',
  `MEM_ID_STATE` TINYINT(1) NULL DEFAULT 0 COMMENT '身份別
        0:只有一般會員身份
		1:有小農會員身份',
UNIQUE KEY UK_MEM_MEM_ACC (MEM_ACC),
  PRIMARY KEY (`MEM_ID`))
COMMENT = '一般會員',
AUTO_INCREMENT = 77000;

INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('sue112233@gmail.com', 'sue112233', 1, '蘇東坡', 
		'甚麼咚咚', 0915524586, 03926933, 100, '台北市', '大同區',
		'寶寶路1號', STR_TO_DATE('1981-11-17','%Y-%m-%d'),0,0,0,0,0,0);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Bric1937@superrito.com', 'Bric1937', 1, '吳宛孝', 
		'冰薇', 0953452808, 043950961, 100, '苗栗縣', '後龍鎮',
		'造豐路89巷22號', STR_TO_DATE('2020-11-17','%Y-%m-%d'),393,101,147,35,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Fulta1976@jourrapide.com', 'Fulta1976', 1, '涂子揚', 
		'憐兒', 0939377046, 08238623, 223, '台中市', '南屯區',
		'大敦六街196巷20號4樓', STR_TO_DATE('2020-11-17','%Y-%m-%d'),323,90,145,33,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Hatheyn89@armyspy.com', 'Hatheyn89', 1, '陳宜欣', 
		'天柳', 0952916069, 06685506, 190, '高雄市', '苓雅區',
		'武慶三路107巷26號', STR_TO_DATE('2020-11-18','%Y-%m-%d'),322,85,140,35,1,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Taknoyse1974@dayrep.com', 'Taknoyse1974', 0, '錢志銘', 
		'恨嵐', 0925299062, 06685506, 134, '新北市', '淡水區',
		'新興街50號', STR_TO_DATE('2020-11-19','%Y-%m-%d'),222,65,130,44,1,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Whicer1988@dayrep.com', 'Whicer1988', 1, '陳柏明', 
		'傲菡', 0930583145, 022324357, 121, '嘉義縣', '太保市',
		'祥和三路東段122巷1號', STR_TO_DATE('2020-11-19','%Y-%m-%d'),322,83,190,45,2,0);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Whissind81@superrito.com', 'Whissind81', 1, '趙雅君', 
		'傲雲', 0958977453, 07183176, 148, '台北市', '大安區',
		'新生南路一段65巷8號3樓', STR_TO_DATE('2020-11-22','%Y-%m-%d'),321,77,190,40,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Liek1930@fleckens.hu', 'Liek1930', 1, '洪筱婷', 
		'爾蓮', 0954610031, 022560237, 127, '台中市', '太平區',
		'中山路四段132巷19號', STR_TO_DATE('2020-11-25','%Y-%m-%d'),480,122,233,55,2,0);
                
	
/*小農會員*/
/*70為F之十進位制*/
set auto_increment_offset=70000;
set auto_increment_increment=1;
CREATE TABLE `CFA104G2`.`F_MEM` (
  `F_MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '小農會員編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `ACC_STATE` TINYINT(1) NOT NULL COMMENT '帳號狀態\n0: 帳號未啟用(未審核)\n1: 帳號已啟用(已審核)\n2: 帳號停權',
  `F_MEM_FNAME` VARCHAR(15) NOT NULL COMMENT '農場名稱',
  `F_MEM_INFO` VARCHAR(500) NULL COMMENT '小農簡介',
  `F_MEM_MOBILE` VARCHAR(10) NOT NULL COMMENT '手機',
  `F_MEM_TEL` VARCHAR(10) NULL COMMENT '市話',
  `F_MEM_ZIPCODE` INT NOT NULL COMMENT '郵遞區號',
  `F_MEM_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `F_MEM_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `F_MEM_ADD` VARCHAR(40) NOT NULL COMMENT '地址',
  `BANK_CODE` INT NULL COMMENT '銀行代碼',
  `BANK_ACCOUNT` VARCHAR(20) NULL COMMENT '銀行帳號',
  `REG_DATE` DATETIME NOT NULL COMMENT '加入時間',
  `F_MEM_PIC` LONGBLOB NULL COMMENT '小農頭貼',
  `RATING_SCORE_MK` INT NULL COMMENT '商城總分數',
  `RATING_COUNT_MK` INT NULL COMMENT '商城總評價數',
  `RATING_SCORE_TR` INT NULL COMMENT '旅遊總分數',
  `RATING_COUNT_TR` INT NULL COMMENT '旅遊總評價數',
  `REPORT_COUNT` TINYINT(1) NULL COMMENT '被檢舉計點',
  `ORGANIC_CERTI` LONGBLOB NULL COMMENT '有機認證照片',
  `ENV_FRIENDLY_CERTI` LONGBLOB NULL COMMENT '友善環境認證照片',
  `CERTI_STATE` TINYINT(1) NOT NULL COMMENT '認證狀態',
	CONSTRAINT `FK_F_MEM_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`F_MEM_ID`))
COMMENT = '小農會員',
AUTO_INCREMENT = 70000;

/*1-2.私訊紀錄*/
CREATE TABLE `CFA104G2`.`PRIVATE_MESSAGE` (
  `P_MSG_ID` INT NOT NULL AUTO_INCREMENT COMMENT '私訊編號',
  `MEM_ID` INT NOT NULL COMMENT '會員編號',
  `F_MEM_ID` INT NOT NULL COMMENT '小農會員編號',
  `P_MSG_DIRECT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '訊息發送方向0 : 會員對小農
		1 : 小農對會員',
  `P_MSG_TIME` DATETIME NOT NULL COMMENT '訊息發送時間',
  `P_MSG_CONTEXT` VARCHAR(800) NULL COMMENT '訊息內容',
  `P_MSG_IMG` LONGBLOB NULL COMMENT '圖片訊息',
  PRIMARY KEY (`P_MSG_ID`),
  INDEX `P_MSG_ID_idx` (`P_MSG_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PRIVATE_MESSAGE_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `F_MEM_ID`
    FOREIGN KEY (`F_MEM_ID`)
    REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '私訊紀錄';

/*1-1.訊息通知*/
CREATE TABLE `CFA104G2`.`MESSAGE` (
  `MSG_NO` INT NOT NULL AUTO_INCREMENT COMMENT '通知訊息編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `MEM_ID_SEND` INT NULL COMMENT '發訊會員編號',
  `MSG_TIME` DATETIME NOT NULL COMMENT '通知時間',
  `MSG` VARCHAR(40) NULL COMMENT '訊息內容',
  `READ_STATE` TINYINT(1) NOT NULL COMMENT '讀取狀態\n0:未讀\n1:已讀',
  PRIMARY KEY (`MSG_NO`),
  CONSTRAINT `FK_MESSAGE_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

