/*管理員區資料重刷*/
CREATE DATABASE IF NOT EXISTS `CFA104G2`;

USE `CFA104G2`;

DROP TABLE IF EXISTS `HOME_SLIDESHOW`;
DROP TABLE IF EXISTS `ANNOUNCEMENT`;
DROP TABLE IF EXISTS `ADMIN_FUNC_LIST`;
DROP TABLE IF EXISTS `FUNCTION`;
DROP TABLE IF EXISTS `ADMINISTRATOR`;
DROP TABLE IF EXISTS `ADMIN_TYPE`;

/*建立管理類別表*/
CREATE TABLE `CFA104G2`.`ADMIN_TYPE` (
  `ADMIN_TYPE_ID` INT NOT NULL COMMENT '管理類別編號',
  `ADMIN_TYPE_NAME` VARCHAR(20) NOT NULL COMMENT '管理類別名稱',
  PRIMARY KEY (`ADMIN_TYPE_ID`))
COMMENT '管理類別表';

/*建立管理員資料*/
CREATE TABLE `CFA104G2`.`ADMINISTRATOR` (
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `ADMIN_TYPE_ID` INT NOT NULL COMMENT '管理員類別編號',
  `ADMIN_ACC` VARCHAR(20) NOT NULL COMMENT '帳號',
  `ADMIN_PWD` VARCHAR(20) NOT NULL COMMENT '密碼',
  `ADMIN_ISDELETED` TINYINT(1) NOT NULL COMMENT '帳號狀態\n0:帳號失效\n1:帳號有效',
  `ADMIN_NAME` VARCHAR(20) NOT NULL COMMENT '姓名',
  `ADMIN_EMAIL` VARCHAR(40) NOT NULL COMMENT '信箱',
  `ADMIN_ZIPCODE` TINYINT(3) NOT NULL COMMENT '郵遞區號',
  `ADMIN_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `ADMIN_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `ADMIN_ADDR` VARCHAR(40) NOT NULL COMMENT '地址',
  `ADMIN_HIREDATE` DATETIME NOT NULL COMMENT '到職日',
  `ADMIN_LEAVEDATE` DATETIME NOT NULL COMMENT '離職日',
  `ADMIN_PIC` LONGBLOB NULL COMMENT '員工照片',
  PRIMARY KEY (`ADMIN_ID`),
  CONSTRAINT `ADMIN_TYPE_ID`
    FOREIGN KEY (`ADMIN_TYPE_ID`)
    REFERENCES `CFA104G2`.`ADMIN_TYPE` (`ADMIN_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '管理員資料';

/*建立功能權限表*/    
CREATE TABLE `CFA104G2`.`FUNCTION` (
  `FUNC_ID` INT NOT NULL COMMENT '功能編號',
  `FUNC_NAME` VARCHAR(20) NOT NULL COMMENT '功能名稱',
  `FUNC_DES` VARCHAR(100) NOT NULL COMMENT '功能敘述',
  PRIMARY KEY (`FUNC_ID`))
COMMENT = '類別功能對照表';

/*建立類別功能對照表*/
CREATE TABLE `CFA104G2`.`ADMIN_FUNC_LIST` (
  `ADMIN_TYPE_ID` INT NOT NULL,
  `FUNC_ID` INT NOT NULL,
  PRIMARY KEY (`ADMIN_TYPE_ID`, `FUNC_ID`),
  FOREIGN KEY (`ADMIN_TYPE_ID`)
  REFERENCES `CFA104G2`.`ADMIN_TYPE` (`ADMIN_TYPE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,  
  FOREIGN KEY (`FUNC_ID`)
  REFERENCES `CFA104G2`.`FUNCTION` (`FUNC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
COMMENT = '類別功能對照表';

/*建立系統公告*/    
CREATE TABLE `CFA104G2`.`ANNOUNCEMENT` (
  `ANNOUNCE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '公告編號',
  `ANNOUNCE_TYPE` TINYINT(1) NOT NULL COMMENT '公告種類\n0:最新消息\n1:活動訊息\n2:平台公告',
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `EDIT_TIME` DATETIME NOT NULL COMMENT '發布時間',
  `ANNOUNCE_TITLE` VARCHAR(40) NOT NULL COMMENT '公告標題',
  `ANNOUNCE_CONTEN` VARCHAR(1200) NOT NULL COMMENT '公告內容',
  PRIMARY KEY (`ANNOUNCE_ID`),
  CONSTRAINT `ADMIN_ID`
    FOREIGN KEY (`ADMIN_ID`)
    REFERENCES `CFA104G2`.`ADMINISTRATOR` (`ADMIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '系統公告';

/*建立首頁幻燈片*/    
CREATE TABLE `CFA104G2`.`HOME_SLIDESHOW` (
  `HSS_ID` INT NOT NULL AUTO_INCREMENT COMMENT '幻燈片編號',
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `HSS_IMG` BLOB NULL COMMENT '圖片',
  `HSS_TEXT` VARCHAR(80) NOT NULL COMMENT '圖片描述',
  `HSS_TIME` TIMESTAMP NOT NULL COMMENT '發布時間',
  `HSS_STATE` TINYINT(1) NOT NULL COMMENT '圖片狀態',
  `HSS_ON_SHELF` DATETIME NOT NULL COMMENT '上架時間',
  `HSS_OFF_SHELF` DATETIME NOT NULL COMMENT '下架時間',
  PRIMARY KEY (`HSS_ID`),
  FOREIGN KEY (`ADMIN_ID`)
  REFERENCES `CFA104G2`.`ADMINISTRATOR` (`ADMIN_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
COMMENT = '首頁幻燈片';