CREATE DATABASE IF NOT EXISTS CFA104G2;

use CFA104G2;
/********************移除管理員所有資料表********************/
DROP TABLE IF EXISTS `HOME_SLIDESHOW`;
DROP TABLE IF EXISTS `ANNOUNCEMENT`;
DROP TABLE IF EXISTS `ADMIN_FUNC_LIST`;
DROP TABLE IF EXISTS `FUNCTION`;
DROP TABLE IF EXISTS `ADMINISTRATOR`;
DROP TABLE IF EXISTS `ADMIN_TYPE`;


/********************移除認養所有資料表********************/
DROP TABLE IF EXISTS `PROJ_DISCUSSION`;
DROP TABLE IF EXISTS `PROJ_REPORT`;
DROP TABLE IF EXISTS `PROJ_ORDER`;
DROP TABLE IF EXISTS `PROJ_PERK`;
DROP TABLE IF EXISTS `PROJ_COLLECTION`;
DROP TABLE IF EXISTS `PROJ_DIARY_PIC`;
DROP TABLE IF EXISTS `PROJ_DIARY`;
DROP TABLE IF EXISTS `PROJ_PIC`;
DROP TABLE IF EXISTS `PROJECT`;


/********************移除農遊所有資料表********************/
DROP TABLE IF EXISTS FARM_TRAVEL_PARTNER;
DROP TABLE IF EXISTS FARM_TRAVEL_ORDER;
DROP TABLE IF EXISTS FARM_TRAVEL_COLLECTION;
DROP TABLE IF EXISTS FARM_TRAVEL_REPORT;
DROP TABLE IF EXISTS FARM_TRAVEL_TAG_DETAILS;
DROP TABLE IF EXISTS FARM_TRAVEL_TAG;
DROP TABLE IF EXISTS FARM_TRAVEL;


/********************移除論壇所有資料表********************/
DROP TABLE IF EXISTS COMMENTS_REPORT;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS ARTICLE_REPORT;
DROP TABLE IF EXISTS ARTICLE_COLLECTION;
DROP TABLE IF EXISTS ARTICLE_PIC;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS ARTICLE_TYPE;


/********************移除商城所有資料表********************/
DROP TABLE IF EXISTS `SHOP_HASHTAG_DETAILS`;
DROP TABLE IF EXISTS `SHOP_HASHTAG_PRODUCT`;
DROP TABLE IF EXISTS `SHOP_CARTLIST`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_COLLECTION`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_REPORT`;
DROP TABLE IF EXISTS `SHOP_ORDER_DETAILS`;
DROP TABLE IF EXISTS `SHOP_ORDER`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_PIC`;
DROP TABLE IF EXISTS `SHOP_PRODUCT`;
DROP TABLE IF EXISTS `SHOP_PRODUCT_TYPE`;


/********************移除會員小農所有資料表********************/
DROP TABLE IF EXISTS `PRIVATE_MESSAGE`;
DROP TABLE IF EXISTS `MESSAGE`;
DROP TABLE IF EXISTS `F_MEM`;
DROP TABLE IF EXISTS `MEM`;


/********************會員小農資料表區********************/
/*一般會員*/
/*77為M之十進位制*/
set auto_increment_offset=77000;
set auto_increment_increment=1;
CREATE TABLE `CFA104G2`.`MEM` (
  `MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '一般會員編號',
  `MEM_ACC` VARCHAR(40) NOT NULL COMMENT '帳號',
  `MEM_PWD` VARCHAR(20) NOT NULL COMMENT '密碼',
  `ACC_STATE` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '帳號狀態',
  `MEM_NAME` VARCHAR(20) NOT NULL COMMENT '姓名',
  `MEM_NICKNAME` VARCHAR(20) NOT NULL COMMENT '暱稱',
  `MEM_MOBILE` VARCHAR(10) NOT NULL COMMENT '手機',
  `MEM_TEL` VARCHAR(10) NULL COMMENT '市話',
  `MEM_ZIPCODE` INT NOT NULL COMMENT '郵遞區號',
  `MEM_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `MEM_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `MEM_ADDR` VARCHAR(40) NOT NULL COMMENT '地址',
  `REG_DATE` DATETIME NOT NULL COMMENT '加入時間',
  `MEM_PIC` LONGBLOB NULL COMMENT '會員頭貼',
  `RATING_SCORE_MK` INT NULL COMMENT '商城總分數',
  `RATING_COUNT_MK` INT NULL COMMENT '商城總評價數',
  `RATING_SCORE_TR` INT NULL COMMENT '旅遊總分數',
  `RATING_COUNT_TR` INT NULL COMMENT '旅遊總評價數',
  `REPORT_COUNT` TINYINT(2) NULL COMMENT '被檢舉計點',
  `MEM_ID_STATE` TINYINT(1) NULL DEFAULT 0 COMMENT '身份別
        0:只有一般會員身份
		1:有小農會員身份',
UNIQUE KEY UK_MEM_MEM_ACC (MEM_ACC),
  PRIMARY KEY (`MEM_ID`))
COMMENT = '一般會員',
AUTO_INCREMENT = 77000;

INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('sue112233@gmail.com', 'sue112233', 1, '蘇東坡', 
		'甚麼咚咚', 0915524586, 03926933, 100, '台北市', '大同區',
		'寶寶路1號', STR_TO_DATE('1981-11-17','%Y-%m-%d'),0,0,0,0,0,0);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Bric1937@superrito.com', 'Bric1937', 1, '吳宛孝', 
		'冰薇', 0953452808, 043950961, 100, '苗栗縣', '後龍鎮',
		'造豐路89巷22號', STR_TO_DATE('2020-11-17','%Y-%m-%d'),393,101,147,35,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Fulta1976@jourrapide.com', 'Fulta1976', 1, '涂子揚', 
		'憐兒', 0939377046, 08238623, 223, '台中市', '南屯區',
		'大敦六街196巷20號4樓', STR_TO_DATE('2020-11-17','%Y-%m-%d'),323,90,145,33,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Hatheyn89@armyspy.com', 'Hatheyn89', 1, '陳宜欣', 
		'天柳', 0952916069, 06685506, 190, '高雄市', '苓雅區',
		'武慶三路107巷26號', STR_TO_DATE('2020-11-18','%Y-%m-%d'),322,85,140,35,1,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Taknoyse1974@dayrep.com', 'Taknoyse1974', 0, '錢志銘', 
		'恨嵐', 0925299062, 06685506, 134, '新北市', '淡水區',
		'新興街50號', STR_TO_DATE('2020-11-19','%Y-%m-%d'),222,65,130,44,1,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Whicer1988@dayrep.com', 'Whicer1988', 1, '陳柏明', 
		'傲菡', 0930583145, 022324357, 121, '嘉義縣', '太保市',
		'祥和三路東段122巷1號', STR_TO_DATE('2020-11-19','%Y-%m-%d'),322,83,190,45,2,0);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Whissind81@superrito.com', 'Whissind81', 1, '趙雅君', 
		'傲雲', 0958977453, 07183176, 148, '台北市', '大安區',
		'新生南路一段65巷8號3樓', STR_TO_DATE('2020-11-22','%Y-%m-%d'),321,77,190,40,0,1);
INSERT INTO MEM (
	MEM_ACC, MEM_PWD, ACC_STATE, MEM_NAME, MEM_NICKNAME, 
    MEM_MOBILE, MEM_TEL, MEM_ZIPCODE, MEM_CITY, MEM_DIST, MEM_ADDR,
    REG_DATE, RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,
    RATING_COUNT_TR, REPORT_COUNT, MEM_ID_STATE)  
    VALUES 
    ('Liek1930@fleckens.hu', 'Liek1930', 1, '洪筱婷', 
		'爾蓮', 0954610031, 022560237, 127, '台中市', '太平區',
		'中山路四段132巷19號', STR_TO_DATE('2020-11-25','%Y-%m-%d'),480,122,233,55,2,0);
                
	
/*小農會員*/
/*70為F之十進位制*/
set auto_increment_offset=70000;
set auto_increment_increment=1;
CREATE TABLE `CFA104G2`.`F_MEM` (
  `F_MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '小農會員編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `ACC_STATE` TINYINT(1) NOT NULL COMMENT '帳號狀態\n0: 帳號未啟用(未審核)\n1: 帳號已啟用(已審核)\n2: 帳號停權',
  `F_MEM_FNAME` VARCHAR(15) NOT NULL COMMENT '農場名稱',
  `F_MEM_INFO` VARCHAR(500) NULL COMMENT '小農簡介',
  `F_MEM_MOBILE` VARCHAR(10) NOT NULL COMMENT '手機',
  `F_MEM_TEL` VARCHAR(10) NULL COMMENT '市話',
  `F_MEM_ZIPCODE` INT NOT NULL COMMENT '郵遞區號',
  `F_MEM_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `F_MEM_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `F_MEM_ADD` VARCHAR(40) NOT NULL COMMENT '地址',
  `BANK_CODE` INT NULL COMMENT '銀行代碼',
  `BANK_ACCOUNT` VARCHAR(20) NULL COMMENT '銀行帳號',
  `REG_DATE` DATETIME NOT NULL COMMENT '加入時間',
  `F_MEM_PIC` LONGBLOB NULL COMMENT '小農頭貼',
  `RATING_SCORE_MK` INT NULL COMMENT '商城總分數',
  `RATING_COUNT_MK` INT NULL COMMENT '商城總評價數',
  `RATING_SCORE_TR` INT NULL COMMENT '旅遊總分數',
  `RATING_COUNT_TR` INT NULL COMMENT '旅遊總評價數',
  `REPORT_COUNT` TINYINT(1) NULL COMMENT '被檢舉計點',
  `ORGANIC_CERTI` LONGBLOB NULL COMMENT '有機認證照片',
  `ENV_FRIENDLY_CERTI` LONGBLOB NULL COMMENT '友善環境認證照片',
  `CERTI_STATE` TINYINT(1) NOT NULL COMMENT '認證狀態',
	CONSTRAINT `FK_F_MEM_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  PRIMARY KEY (`F_MEM_ID`))
COMMENT = '小農會員',
AUTO_INCREMENT = 70000;

INSERT INTO F_MEM (
	MEM_ID, ACC_STATE, F_MEM_FNAME, 
    F_MEM_INFO, 
    F_MEM_MOBILE, F_MEM_TEL, F_MEM_ZIPCODE, F_MEM_CITY, F_MEM_DIST, F_MEM_ADD,
    BANK_CODE, BANK_ACCOUNT, REG_DATE, 
    RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,RATING_COUNT_TR, REPORT_COUNT, CERTI_STATE)  
    VALUES 
    (77005, 1, '鴞瑯農場', 
		'提供多元的生態樣貌及體驗活動，不僅是老少咸宜的休閒場所，也是親子遊憩的最佳選擇！ 
        園區遍植數百種水生、陸生的原生種植物，還有螢火蟲、蝴蝶、竹節蟲、甲蟲等多種昆蟲等你來認識。 
        自動介紹。定位地圖不迷路。服務: 導覽介紹, 定位導航, 遊記分享。',
		0930583145, 022324357, 121, '嘉義縣', '太保市','祥和三路東段122巷1號', 
        422, '441180038329',STR_TO_DATE('2020-11-19','%Y-%m-%d'),
        322,83,190,45,2,0);
        
INSERT INTO F_MEM (
	MEM_ID, ACC_STATE, F_MEM_FNAME, 
    F_MEM_INFO, 
    F_MEM_MOBILE, F_MEM_TEL, F_MEM_ZIPCODE, F_MEM_CITY, F_MEM_DIST, F_MEM_ADD,
    BANK_CODE, BANK_ACCOUNT, REG_DATE, 
    RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,RATING_COUNT_TR, REPORT_COUNT, CERTI_STATE)  
    VALUES 
    (77004, 0, '嘯月農場', 
		'無汙染的空氣洄瀾淨土，是最佳的有機園區。我們秉持四句諫言：
        良心善心菩提心、春夏秋冬本無物、東西南北觀自在、知福惜福再造福。
        致力於有機農作物生產，時時刻刻提醒員工尊重大自然之萬物，以達成天助、人助、自助之目標。', 
        0925299062, 06685506, 134, '新北市', '淡水區', '新興街50號',
		415, '170967442682', STR_TO_DATE('2020-11-19','%Y-%m-%d'),
        222,65,130,44,1,1);
        
	INSERT INTO F_MEM (
	MEM_ID, ACC_STATE, F_MEM_FNAME, 
    F_MEM_INFO, 
    F_MEM_MOBILE, F_MEM_TEL, F_MEM_ZIPCODE, F_MEM_CITY, F_MEM_DIST, F_MEM_ADD,
    BANK_CODE, BANK_ACCOUNT, REG_DATE, 
    RATING_SCORE_MK, RATING_COUNT_MK, RATING_SCORE_TR,RATING_COUNT_TR, REPORT_COUNT, CERTI_STATE)  
    VALUES 
    (77006, 1, '小柏農場',
		'山環抱視野遼闊，四季明媚景色萬千，晨昏彩霞驚艷動人，擁有獨特的高山田園景觀，
        出產的高山茶(福壽長春茶)與水果(蜜蘋果、水蜜桃、水梨等)品質精良，旅遊中心提供舒適的住宿與用餐，
        是闔家出遊、探尋秘境的絕佳景點。', 
        0958977453, 07183176, 148, '台北市', '大安區', '新生南路一段65巷8號3樓', 
        553, '803878963431',STR_TO_DATE('2020-11-22','%Y-%m-%d'),
        321,77,190,40,0,1);


/*1-2.私訊紀錄*/
CREATE TABLE `CFA104G2`.`PRIVATE_MESSAGE` (
  `P_MSG_ID` INT NOT NULL AUTO_INCREMENT COMMENT '私訊編號',
  `MEM_ID` INT NOT NULL COMMENT '會員編號',
  `F_MEM_ID` INT NOT NULL COMMENT '小農會員編號',
  `P_MSG_DIRECT` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '訊息發送方向0 : 會員對小農
		1 : 小農對會員',
  `P_MSG_TIME` DATETIME NOT NULL COMMENT '訊息發送時間',
  `P_MSG_CONTEXT` VARCHAR(800) NULL COMMENT '訊息內容',
  `P_MSG_IMG` LONGBLOB NULL COMMENT '圖片訊息',
  PRIMARY KEY (`P_MSG_ID`),
  INDEX `P_MSG_ID_idx` (`P_MSG_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PRIVATE_MESSAGE_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRIVATE_MESSAGE_F_MEM_ID`
    FOREIGN KEY (`F_MEM_ID`)
    REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '私訊紀錄';


/*1-1.訊息通知*/
CREATE TABLE `CFA104G2`.`MESSAGE` (
  `MSG_NO` INT NOT NULL AUTO_INCREMENT COMMENT '通知訊息編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `MEM_ID_SEND` INT NULL COMMENT '發訊會員編號',
  `MSG_TIME` DATETIME NOT NULL COMMENT '通知時間',
  `MSG` VARCHAR(40) NULL COMMENT '訊息內容',
  `READ_STATE` TINYINT(1) NOT NULL COMMENT '讀取狀態\n0:未讀\n1:已讀',
  PRIMARY KEY (`MSG_NO`),
  CONSTRAINT `FK_MESSAGE_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


/****************************************/


/********************商城資料表區********************/
/*2-3.商品類別*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_TYPE` (
  `PROD_TYPE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品類別編號',
  `PROD_TYPE_NAME` VARCHAR(20) NOT NULL COMMENT '商品類別名稱',
  PRIMARY KEY (`PROD_TYPE_ID`))
COMMENT = '2-3.商品類別';

/*2-1.商城商品*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT` (
  `PROD_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品編號',
  `PROD_TYPE_ID` INT NOT NULL COMMENT '商品類別編號',
  `PROD_NAME` VARCHAR(40) NOT NULL COMMENT '商品名稱',
  `F_MEM_ID` INT NOT NULL COMMENT '小農會員編號',
  `PROD_STATUS` TINYINT NOT NULL COMMENT '商品狀態',
  `PROD_PRICE` INT NOT NULL COMMENT '商品價格',
  `PROD_QTY` INT NOT NULL COMMENT '商品數量',
  `PROD_INTRO` VARCHAR(800) NOT NULL COMMENT '商品介紹',
  `PROD_REG_DATE` DATETIME NOT NULL COMMENT '商品上架日期',
  PRIMARY KEY (`PROD_ID`),
  INDEX `F_MEM_ID_idx` (`F_MEM_ID` ASC) VISIBLE,
  INDEX `PROD_TYPE_ID_idx` (`PROD_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_PRODUCT_F_MEM_ID`
    FOREIGN KEY (`F_MEM_ID`)
    REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
   CONSTRAINT `FK_SHOP_PRODUCT_PROD_TYPE_ID`
	FOREIGN KEY (`PROD_TYPE_ID`)
	REFERENCES `CFA104G2`.`SHOP_PRODUCT_TYPE` (`PROD_TYPE_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '2-1商城商品';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT` 
DROP FOREIGN KEY `FK_SHOP_PRODUCT_F_MEM_ID`,
DROP FOREIGN KEY `FK_SHOP_PRODUCT_PROD_TYPE_ID`;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_F_MEM_ID`
  FOREIGN KEY (`F_MEM_ID`)
  REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`),
ADD CONSTRAINT `FK_SHOP_PRODUCT_PROD_TYPE_ID`
  FOREIGN KEY (`PROD_TYPE_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT_TYPE` (`PROD_TYPE_ID`);


/*2-2.商城商品照片 */
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_PIC` (
  `PROD_PIC_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商品圖片編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `PROD_PIC` LONGBLOB NULL COMMENT '商品圖片',
  PRIMARY KEY (`PROD_PIC_ID`),
  INDEX `PROD_ID_idx` (`PROD_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_PRODUCT_PIC_PROD_ID`
    FOREIGN KEY (`PROD_ID`)
    REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '2-2.商城商品照片';


/*2-4.商城訂單*/
CREATE TABLE `CFA104G2`.`SHOP_ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT COMMENT '商城訂單編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `ORDER_DATE` DATETIME NOT NULL COMMENT '訂單日期',
  `ORDER_SHIPMENT` TINYINT NOT NULL COMMENT '出貨方式',
  `ORDER_SHIP_FEE` INT NOT NULL COMMENT '運費',
  `ORDER_AMOUNT` DECIMAL NOT NULL COMMENT '總金額',
  `ORDER_PAYMENT` TINYINT NOT NULL COMMENT '付款方式',
  `RETURN_RULE` TINYINT NOT NULL COMMENT '退貨規範\n0:退款  1:退貨   2:需協商',
  `ORDER_MEMO` VARCHAR(20) NULL COMMENT '訂單備註',
  `ORDER_SHIP_DATE` DATETIME NOT NULL COMMENT '出貨日期',
  `ORDER_STATE` TINYINT NOT NULL COMMENT '訂單狀態\n0: 等待付款中  1: 已取消  2: 等待賣家確認中  3: 出貨準備中  4: 已出貨  5: 未取貨，退回賣家 ',
  PRIMARY KEY (`ORDER_ID`),
  INDEX `MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
  CONSTRAINT `FK_SHOP_ORDER_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '2-4.商城訂單';

ALTER TABLE `CFA104G2`.`SHOP_ORDER` 
DROP FOREIGN KEY `FK_SHOP_ORDER_MEM_ID`;
ALTER TABLE `CFA104G2`.`SHOP_ORDER` 
ADD CONSTRAINT `FK_SHOP_ORDER_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`);


/*2-5.商城訂單明細*/
CREATE TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` (
  `ORDER_ID` INT NOT NULL COMMENT '商城訂單編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `ORDER_QTY` INT NOT NULL COMMENT '購買數量',
  `ORDER_UNIT_PRICE` INT NOT NULL COMMENT '單價',
  `PROD_ID_STARS` INT NULL COMMENT '商品星數',
  `MEM_ID_STARS` INT NULL COMMENT '一般會員星數',
  PRIMARY KEY (`ORDER_ID`, `PROD_ID`))
COMMENT = '2-5.商城訂單明細';

ALTER TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` 
ADD INDEX `FK_SHOP_ORDER_DETAILS_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_ORDER_DETAILS` 
ADD CONSTRAINT `FK_SHOP_ORDER_DETAILS_ORDER_ID`
  FOREIGN KEY (`ORDER_ID`)
  REFERENCES `CFA104G2`.`SHOP_ORDER` (`ORDER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_ORDER_DETAILS_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*2-6.商品檢舉單*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` (
  `PROD_REPORT_NO` INT NOT NULL AUTO_INCREMENT COMMENT '商品檢舉編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `REPORT_REASON` VARCHAR(800) NOT NULL COMMENT '檢舉事由',
  `REPORT_TIME` DATETIME NOT NULL COMMENT '檢舉日期',
  `REPORT_STATE` TINYINT NOT NULL COMMENT '檢舉狀態\n0: 未處理\n1: 檢舉通過\n2: 檢舉未通過',
  `REPORT_NOTE` VARCHAR(300) NULL COMMENT '檢舉備註',
  PRIMARY KEY (`PROD_REPORT_NO`))
COMMENT = '2-6.商品檢舉單';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` 
ADD INDEX `FK_SHOP_PRODUCT_REPORT_MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
ADD INDEX `FK_SHOP_PRODUCT_REPORT_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_REPORT` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_REPORT_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_PRODUCT_REPORT_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*2-7.商品收藏列表*/
CREATE TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` (
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `PROD_FAV_DATE` DATETIME NOT NULL COMMENT '加入收藏日期',
  PRIMARY KEY (`MEM_ID`, `PROD_ID`))
COMMENT = '2-7.商品收藏列表';

ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` 
ADD INDEX `FK_SHOP_PRODUCT_COLLECTION_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_PRODUCT_COLLECTION` 
ADD CONSTRAINT `FK_SHOP_PRODUCT_COLLECTION_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_PRODUCT_COLLECTION_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*2-8.商城購物車列表*/
CREATE TABLE `CFA104G2`.`SHOP_CARTLIST` (
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  `CARTLIST_QTY` INT NOT NULL COMMENT '購買數量',
  `CARTLIST_UNIT_PRICE` INT NOT NULL COMMENT '單價',
  PRIMARY KEY (`MEM_ID`,`PROD_ID`))
COMMENT = '2-8.商城購物車列表';

ALTER TABLE `CFA104G2`.`SHOP_CARTLIST` 
ADD INDEX `FK_SHOP_CARTLIST_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_CARTLIST` 
ADD CONSTRAINT `FK_SHOP_CARTLIST_MEM_ID`
  FOREIGN KEY (`MEM_ID`)
  REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_CARTLIST_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


/*2-9.商品主題標籤*/
CREATE TABLE `CFA104G2`.`SHOP_HASHTAG_PRODUCT` (
  `HASH_NO` INT NOT NULL COMMENT '商品主題標籤編號',
  `HASH_KEY` VARCHAR(45) NOT NULL COMMENT '商品主題關鍵字',
  PRIMARY KEY (`HASH_NO`))
COMMENT = '2-9.商品主題標籤';


/*2-10.商品主題標籤明細*/
CREATE TABLE `CFA104G2`.`SHOP_HASHTAG_DETAILS` (
  `HASH_NO` INT NOT NULL COMMENT '商品主題標籤編號',
  `PROD_ID` INT NOT NULL COMMENT '商品編號',
  PRIMARY KEY (`HASH_NO`, `PROD_ID`))
COMMENT = '2-10.商品主題標籤明細';

ALTER TABLE `CFA104G2`.`SHOP_HASHTAG_DETAILS` 
ADD INDEX `FK_SHOP_HASHTAG_DETAILS_PROD_ID_idx` (`PROD_ID` ASC) VISIBLE;
;
ALTER TABLE `CFA104G2`.`SHOP_HASHTAG_DETAILS` 
ADD CONSTRAINT `FK_SHOP_HASHTAG_DETAILS_HASH_NO`
  FOREIGN KEY (`HASH_NO`)
  REFERENCES `CFA104G2`.`SHOP_HASHTAG_PRODUCT` (`HASH_NO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `FK_SHOP_HASHTAG_DETAILS_PROD_ID`
  FOREIGN KEY (`PROD_ID`)
  REFERENCES `CFA104G2`.`SHOP_PRODUCT` (`PROD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
/****************************************/ 


/********************農遊資料表區********************/ 
/*4-1.農遊行程*/
CREATE TABLE FARM_TRAVEL(
 FARM_TRAVEL_ID INT NOT NULL PRIMARY KEY auto_increment comment "農遊行程編號",
 MEM_ID INT Not Null comment "一般會員編號",
 F_MEM_ID INT Not Null comment "小農編號",
 FARM_TRAVEL_TITLE VARCHAR(50) Not Null comment "農遊標題",
 FARM_TRAVEL_IMG LONGBLOB comment "農遊封面圖",
 FARM_TRAVEL_INFO VARCHAR(1500) Not Null comment "農遊資訊",
 FARM_TRAVEL_START DATETIME Not Null comment "農遊行程起",
 FARM_TRAVEL_END DATETIME Not Null comment "農遊行程迄",
 FARM_TRAVEL_FEE INT Not Null comment "農遊費用",
 TRAVEL_APPLY_START DATETIME Not Null comment "農遊報名開始",
 TRAVEL_APPLY_END DATETIME Not Null comment "農遊報名截止",
 FARM_TRAVEL_MIN INT Not Null comment "最少人數",
 FARM_TRAVEL_MAX INT Not Null comment "最大人數",
 FARM_TRAVEL_NOW INT Not Null comment "目前報名人數",
 FARM_TRAVEL_STATE TINYINT Not Null comment "農遊狀態 0:未開放 1:報名中 2:已成團 3:已額滿 4:已取消",
 FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
 FOREIGN KEY(F_MEM_ID) REFERENCES F_MEM(F_MEM_ID)
);

/*4-2.農遊訂單*/
CREATE TABLE FARM_TRAVEL_ORDER(
 ORDER_ID INT Not Null PRIMARY KEY auto_increment comment "訂單編號",
 MEM_ID INT Not Null comment "一般會員編號",
 FARM_TRAVEL_ID INT Not Null comment "農遊行程編號",
 F_MEM_ID INT Not Null comment "小農會員編號",
 ORDER_TIME DATETIME Not Null comment "訂單日期",
 PEOPLE_NUM	INT Not Null comment "報名人數",
 ORDER_FEE INT Not Null comment "訂單金額",
 FARM_TRAVEL_START DATETIME Not Null comment "農遊行程起",
 FARM_TRAVEL_END DATETIME Not Null comment "農遊行程迄",
 ORDER_STATE TINYINT Not Null comment "訂單狀態 0:待付款 1:訂單成立 2:訂單已完成 3:訂單已取消",
 ORDER_PAYMENT TINYINT 	comment "付款方式 0:信用卡 1:銀行轉帳",
 REFUND_TIME DATETIME comment "退款時間",
 FARM_TRAVEL_STARS INT comment "農遊星數",
 MEM_ID_STARS INT comment "會員星數",
 ORDER_MEMO VARCHAR(250) comment "訂單備註",
 FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
 FOREIGN KEY(FARM_TRAVEL_ID) REFERENCES FARM_TRAVEL(FARM_TRAVEL_ID),
 FOREIGN KEY(F_MEM_ID) REFERENCES F_MEM(F_MEM_ID)
);

/*4-3.農遊小夥伴*/
CREATE TABLE FARM_TRAVEL_PARTNER(
 PARTNER_ID INT Not Null comment "農遊小夥伴編號",
 ORDER_ID INT Not Null comment "訂單編號",
 PARTNER_NAME VARCHAR(20) Not Null comment "小夥伴姓名",
 PARTNER_PHONE VARCHAR(20) Not Null comment "小夥伴電話",
 GUARDIAN_NAME VARCHAR(20) Not Null comment "緊急聯絡人",
 GUARDIAN_PHONE VARCHAR(20) Not Null comment "緊急連絡人電話",
 APPLY_MEM_ID INT Not Null comment "報名會員編號",
 FOREIGN KEY(ORDER_ID) REFERENCES FARM_TRAVEL_ORDER(ORDER_ID),
 FOREIGN KEY(APPLY_MEM_ID) REFERENCES FARM_TRAVEL_ORDER(MEM_ID)
);

/*4-4.農遊收藏*/
CREATE TABLE FARM_TRAVEL_COLLECTION(
 MEM_ID INT Not Null comment "會員編號",
 FARM_TRAVEL_ID INT Not Null comment "農遊行程編號",
 COLLECTION_TIME DATETIME Not Null comment "收藏時間",
 FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
 FOREIGN KEY(FARM_TRAVEL_ID) REFERENCES FARM_TRAVEL(FARM_TRAVEL_ID)
);

/*4-5.農遊檢舉*/
CREATE TABLE FARM_TRAVEL_REPORT(
 REPORT_ID INT Not Null PRIMARY KEY auto_increment comment "檢舉單編號",
 MEM_ID INT Not Null comment "一般會員編號",
 FARM_TRAVEL_ID INT Not Null comment "農遊行程編號",
 REPORT_REASON VARCHAR(500) Not Null comment "檢舉事由",
 REPORT_TIME DATETIME Not Null comment "檢舉日期",
 REPORT_STATE TINYINT Not Null comment "檢舉狀態 0:未處理 1:檢舉通過 2:檢舉未通過",
 REPORT_NOTE VARCHAR(300) comment "檢舉備註",
 FOREIGN KEY(FARM_TRAVEL_ID) REFERENCES FARM_TRAVEL(FARM_TRAVEL_ID),
 FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID)
);

/*4-7.農遊標籤*/
CREATE TABLE FARM_TRAVEL_TAG( 
 TAG_ID INT Not Null PRIMARY KEY auto_increment comment "標籤編號",
 TAG_NAME VARCHAR(20) Not Null comment "標籤名稱",
 TAG_TIMES INT Not Null comment "標籤使用次數"
);

/*4-6.農遊標籤明細*/
CREATE TABLE FARM_TRAVEL_TAG_DETAILS(
 FARM_TRAVEL_ID INT Not Null comment "農遊行程編號",
 TAG_ID INT Not Null comment "標籤編號",
 FOREIGN KEY(FARM_TRAVEL_ID) REFERENCES FARM_TRAVEL(FARM_TRAVEL_ID),
 FOREIGN KEY(TAG_ID) REFERENCES FARM_TRAVEL_TAG(TAG_ID)
);
/****************************************/ 


/********************論壇資料表區********************/
/*6-1.文章類別*/
CREATE TABLE ARTICLE_TYPE(
 ARTICLE_TYPE_ID INT NOT NuLL PRIMARY KEY auto_increment comment "文章類別編號",
 ARTICLE_TYPE_IMG LONGBLOB comment "文章類別圖片",
 ARTICLE_TYPE_TEXT VARCHAR(100) Not Null comment "文章類別敘述"
);

/*6-2小農論壇文章*/
CREATE TABLE ARTICLE(
 ARTICLE_ID INT NOT NULL PRIMARY KEY auto_increment comment "文章編號",
 ARTICLE_TITLE VARCHAR(50) Not Null comment "文章標題",
 MEM_ID INT Not Null comment "一般會員編號",
 ARTICLE_TYPE_ID INT Not Null comment "文章類別編號",
 ARTICLE_TIME TIMESTAMP Not Null comment "文章發布時間",
 ARTICLE_CONTENT VARCHAR(3000) Not Null comment "文章內容",
 ARTICLE_IMG LONGBLOB comment "文章首頁圖",
 ARTICLE_LIKE INT Not Null comment "文章讚數",
 COMMENTS_NUM INT Not Null comment "文章留言次數(樓層)",
 ARTICLE_STATE TINYINT  Not Null comment "文章狀態 0 : 顯示 1 : 不顯示",
 FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
 FOREIGN KEY(ARTICLE_TYPE_ID) REFERENCES ARTICLE_TYPE(ARTICLE_TYPE_ID),
 UNIQUE (COMMENTS_NUM)
);

/*6-3.文章照片*/
CREATE TABLE ARTICLE_PIC(
ARTICLE_PIC_ID	INT	Not Null PRIMARY KEY auto_increment comment"文章照片編號",
ARTICLE_ID	INT	Not Null comment"文章編號",
ARTICLE_PIC	LONGBLOB comment"文章照片",
FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
);

/*6-4.小農論壇留言*/
CREATE TABLE COMMENTS(
COMMENTS_ID INT Not Null PRIMARY KEY auto_increment comment "留言編號",
ARTICLE_ID INT Not Null comment "文章編號",
COMMENTS_NUM INT Not Null comment "留言次數(樓層)",
MEM_ID INT Not Null comment "一般會員編號",
COMMENTS_TIME DATETIME Not Null comment "留言時間",
COMMENTS_CONTENT VARCHAR(1000) Not Null comment "留言內容",
COMMENTS_LIKE INT Not Null comment "留言讚數",
COMMENTS_IMG LONGBLOB comment "文章圖片",
COMMENTS_STATE TINYINT Not Null comment "留言狀態 0:顯示 1:不顯示",
FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
FOREIGN KEY(COMMENTS_NUM) REFERENCES ARTICLE(COMMENTS_NUM)
);

/*6-5.小農論壇文章收藏*/
CREATE TABLE ARTICLE_COLLECTION(
ARTICLE_ID	INT	Not Null comment "文章編號",
MEM_ID	INT	Not Null comment "會員編號",
ARTICLE_FOLLOW_DATE	DATETIME Not Null comment "收藏日期",
FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
);

/*6-6.小農論壇文章檢舉*/
CREATE TABLE ARTICLE_REPORT(
ARTICLE_REPORT_ID INT Not Null PRIMARY KEY auto_increment comment "文章檢舉編號",
MEM_ID	INT	 Not Null comment "一般會員編號",
ARTICLE_ID	INT	Not Null comment "文章編號",
REPORT_TIME	DATETIME Not Null comment "檢舉時間",
REPORT_REASON VARCHAR(500) Not Null comment "檢舉事由",
REPORT_STATE TINYINT Not Null comment "檢舉狀態 0: 未處理 1: 檢舉通過 2: 檢舉未通過",
REPORT_NOTE	VARCHAR(300) comment "檢舉備註",
FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)
);

/*6-7.留言檢舉*/
CREATE TABLE COMMENTS_REPORT(
COMMENTS_REPORT_ID INT Not Null PRIMARY KEY auto_increment comment"留言檢舉編號",
ARTICLE_ID INT Not Null comment "文章編號",
COMMENTS_NUM INT Not Null comment "留言次數",
MEM_ID	INT	Not Null comment "一般會員編號",
REPORT_REASON VARCHAR(500) Not Null comment "檢舉事由",
REPORT_TIME	DATETIME Not Null comment "檢舉日期",
REPORT_STATE TINYINT Not Null comment "檢舉狀態 0: 未處理 1: 檢舉通過 2: 檢舉未通過",
REPORT_NOTE	VARCHAR(300) comment "檢舉備註",
FOREIGN KEY(MEM_ID) REFERENCES MEM(MEM_ID),
FOREIGN KEY(ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID),
FOREIGN KEY(COMMENTS_NUM) REFERENCES ARTICLE(COMMENTS_NUM)
);


/****************************************/


/********************認養資料表區********************/
/*5-1.認養專案*/
CREATE TABLE `CFA104G2`.`PROJECT` (
  `PROJ_ID` int NOT NULL AUTO_INCREMENT,
  `F_MEM_ID` int NOT NULL,
  `PROJ_NAME` varchar(40) NOT NULL,
  `PROJ_STATE` tinyint(1) NOT NULL COMMENT '0: 專案待啟動\n1: 專案進行中\n2: 專案已結束',
  `PROJ_MAIN_PIC` LONGBLOB,
  `PROJ_ABSTRACT` varchar(300) NOT NULL,
  `PROJ_GOAL` int NOT NULL,
  `START_DATE` datetime(6) NOT NULL,
  `EXCEPTED_END_DATE` datetime(6) DEFAULT NULL,
  `ACTUAL_END_DATE` datetime(6) DEFAULT NULL,
  `PROJ_TOTAL_FUND` int NOT NULL,
  `PROJ_INTRO` varchar(500) NOT NULL,
  `PROJ_RISK` varchar(500) DEFAULT NULL,
  `PROJ_TOTAL_COUNT` int DEFAULT NULL,
  `PROJ_VIDEO` varchar(100) DEFAULT NULL COMMENT 'youtube文字聯結',
  `MEM_REPORT_COUNT` tinyint DEFAULT NULL,
  `PROJ_PAY` tinyint(1) DEFAULT NULL COMMENT '0:皆可以\n1:信用卡\n2:銀行轉帳',
  PRIMARY KEY (`PROJ_ID`),
  CONSTRAINT `FK_PROJECT_F_MEM_ID`
	FOREIGN KEY (`F_MEM_ID`)
	REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案';


/*5-2.認養專案照片*/
CREATE TABLE `CFA104G2`.`PROJ_PIC` (
  `PROJ_PIC_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `PROJ_PIC` LONGBLOB NULL,
  PRIMARY KEY (`PROJ_PIC_ID`),
  CONSTRAINT `FK_PROJ_DISCUSSION_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養日誌照片';


/*5-4.認養日誌*/
CREATE TABLE `CFA104G2`.`PROJ_DIARY` (
  `DIR_ID` INT NOT NULL AUTO_INCREMENT COMMENT '認養日誌編號',
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `DIR_UPLOAD_DATE` DATETIME NOT NULL COMMENT '日誌日期',
  `DIR_PROCEDURE` VARCHAR(20) NULL COMMENT '生產過程',
  `DIR_PRODUCT` VARCHAR(20) NULL COMMENT '產品/種苗',
  `DIR_EQUIPMENT` VARCHAR(40) NULL COMMENT '器具',
  `DIR_MATERIAL` VARCHAR(100) NULL COMMENT '資材',
  `DIR_EMOJI` VARCHAR(20) NULL COMMENT '心情',
  `DIR_NOTES` VARCHAR(200) NULL COMMENT '心得筆記',
  PRIMARY KEY (`DIR_ID`),
  INDEX `PROJ_ID_idx` (`PROJ_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_DIARY_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養日誌';


/*5-3.認養日誌照片*/
CREATE TABLE `CFA104G2`.`PROJ_DIARY_PIC` (
  `DIR_PIC_ID` INT NOT NULL AUTO_INCREMENT COMMENT '認養日誌照片編號',
  `DIR_ID` INT NOT NULL COMMENT '認養日誌編號',
  `DIR_PIC` LONGBLOB NULL COMMENT '認養日誌照片',
  PRIMARY KEY (`DIR_PIC_ID`),
  CONSTRAINT `FK_PROJ_DIARY_PIC_DIR_ID`
    FOREIGN KEY (`DIR_ID`)
    REFERENCES `CFA104G2`.`PROJ_DIARY` (`DIR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養日誌照片';


/*5-5.認養專案收藏列表*/
CREATE TABLE `CFA104G2`.`PROJ_COLLECTION` (
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  PRIMARY KEY (`PROJ_ID`, `MEM_ID`),
  INDEX `FK_PROJ_COLLECTION_MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_COLLECTION_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_COLLECTION_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養專案收藏列表';


/*5-6.認養回饋方案*/
CREATE TABLE `CFA104G2`.`PROJ_PERK` (
  `PERK_ID` INT NOT NULL AUTO_INCREMENT COMMENT '回饋方案編號',
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `PERK_PIC` LONGBLOB NULL COMMENT '方案插圖',
  `PERK_INTRO` VARCHAR(45) NOT NULL COMMENT '方案文字',
  `PERK_TOTAL_COUNT` INT NOT NULL COMMENT '方案總人數',
  `PERK_TOTAL_FUND` INT NOT NULL COMMENT '方案金額',
  `PERK_LIMITED` INT NULL COMMENT '限量',
  `PERK_SHIP_DATE` DATETIME NOT NULL COMMENT '預計寄送時間',
  `PERK_SHIP_AREA` VARCHAR(45) NOT NULL COMMENT '可寄送區域',
  PRIMARY KEY (`PERK_ID`),
  INDEX `FK_PROJ_PERK_PROJ_ID_idx` (`PROJ_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_PERK_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養回饋方案';


/*5-7.認養訂單*/
CREATE TABLE `CFA104G2`.`PROJ_ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `MEM_ID` INT NOT NULL,
  `PERK_ID` INT NOT NULL,
  `ORDER_TIME` DATETIME NOT NULL,
  `ORDER_ADDR` VARCHAR(40) NOT NULL,
  `ORDER_STATE` TINYINT(1) NOT NULL COMMENT '0 : 待付款\n1 : 待出貨\n2 : 待收貨\n3 : 訂單已完成\n4 : 訂單不成立',
  `ORDER_CANCEL_TIME` DATETIME NULL,
  PRIMARY KEY (`ORDER_ID`),
  CONSTRAINT `FK_PROJ_ORDER_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_ORDER_PERK_ID`
	FOREIGN KEY (`PERK_ID`)
	REFERENCES `CFA104G2`.`PROJ_PERK` (`PERK_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養訂單';


/*5-8.認養專案檢舉單*/
CREATE TABLE `CFA104G2`.`PROJ_REPORT` (
  `PROJ_REPORT_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `MEM_ID` INT NOT NULL,
  `REPORT_REASON` VARCHAR(300) NOT NULL,
  `REPORT_TIME` DATETIME NOT NULL,
  `REPORT_STATE` TINYINT(1) NOT NULL COMMENT '0: 未處理\n1: 檢舉通過\n2: 檢舉未通過',
  `REPORT_NOTE` VARCHAR(300) NULL,
  PRIMARY KEY (`PROJ_REPORT_ID`),
  CONSTRAINT `FK_PROJ_REPORT_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_REPORT_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案檢舉單';


/*5-9.認養專案留言*/
CREATE TABLE `CFA104G2`.`PROJ_DISCUSSION` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `DISCUSSION_ID` INT NOT NULL,
  `MEM_ID` INT NOT NULL,
  `F_MEM_ID` INT NOT NULL,
  `COMMENT_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  CONSTRAINT `FK_PROJECT_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_DISCUSSION_ID`
	FOREIGN KEY (`DISCUSSION_ID`)
	REFERENCES `CFA104G2`.`PROJ_DISCUSSION` (`COMMENT_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_F_MEM_ID`
	FOREIGN KEY (`F_MEM_ID`)
	REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案留言';


/****************************************/


/********************管理員資料表區********************/
/*3-2.建立管理類別表*/
CREATE TABLE `CFA104G2`.`ADMIN_TYPE` (
  `ADMIN_TYPE_ID` INT NOT NULL COMMENT '管理類別編號',
  `ADMIN_TYPE_NAME` VARCHAR(20) NOT NULL COMMENT '管理類別名稱',
  PRIMARY KEY (`ADMIN_TYPE_ID`))
COMMENT '管理類別表';

/*3-1.建立管理員資料*/
CREATE TABLE `CFA104G2`.`ADMINISTRATOR` (
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `ADMIN_TYPE_ID` INT NOT NULL COMMENT '管理員類別編號',
  `ADMIN_ACC` VARCHAR(20) NOT NULL COMMENT '帳號',
  `ADMIN_PWD` VARCHAR(20) NOT NULL COMMENT '密碼',
  `ADMIN_ISDELETED` TINYINT(1) NOT NULL COMMENT '帳號狀態\n0:帳號失效\n1:帳號有效',
  `ADMIN_NAME` VARCHAR(20) NOT NULL COMMENT '姓名',
  `ADMIN_EMAIL` VARCHAR(40) NOT NULL COMMENT '信箱',
  `ADMIN_ZIPCODE` TINYINT(3) NOT NULL COMMENT '郵遞區號',
  `ADMIN_CITY` VARCHAR(5) NOT NULL COMMENT '地址_縣市',
  `ADMIN_DIST` VARCHAR(5) NOT NULL COMMENT '地址_區域',
  `ADMIN_ADDR` VARCHAR(40) NOT NULL COMMENT '地址',
  `ADMIN_HIREDATE` DATETIME NOT NULL COMMENT '到職日',
  `ADMIN_LEAVEDATE` DATETIME NOT NULL COMMENT '離職日',
  `ADMIN_PIC` BLOB NULL COMMENT '員工照片',
  PRIMARY KEY (`ADMIN_ID`),
  CONSTRAINT `ADMIN_TYPE_ID`
    FOREIGN KEY (`ADMIN_TYPE_ID`)
    REFERENCES `CFA104G2`.`ADMIN_TYPE` (`ADMIN_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '管理員資料';

/*3-4.建立功能權限表*/    
CREATE TABLE `CFA104G2`.`FUNCTION` (
  `FUNC_ID` INT NOT NULL COMMENT '功能編號',
  `FUNC_NAME` VARCHAR(20) NOT NULL COMMENT '功能名稱',
  `FUNC_DES` VARCHAR(100) NOT NULL COMMENT '功能敘述',
  PRIMARY KEY (`FUNC_ID`))
COMMENT = '類別功能對照表';

/*3-5.建立類別功能對照表*/
CREATE TABLE `CFA104G2`.`ADMIN_FUNC_LIST` (
  `ADMIN_TYPE_ID` INT NOT NULL,
  `FUNC_ID` INT NOT NULL,
  PRIMARY KEY (`ADMIN_TYPE_ID`, `FUNC_ID`),
  FOREIGN KEY (`ADMIN_TYPE_ID`)
  REFERENCES `CFA104G2`.`ADMIN_TYPE` (`ADMIN_TYPE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,  
  FOREIGN KEY (`FUNC_ID`)
  REFERENCES `CFA104G2`.`FUNCTION` (`FUNC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
COMMENT = '類別功能對照表';

/*3-6.建立系統公告*/
CREATE TABLE `CFA104G2`.`ANNOUNCEMENT` (
  `ANNOUNCE_ID` INT NOT NULL AUTO_INCREMENT COMMENT '公告編號',
  `ANNOUNCE_TYPE` TINYINT(1) NOT NULL COMMENT '公告種類\n0:最新消息\n1:活動訊息\n2:平台公告',
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `EDIT_TIME` DATETIME NOT NULL COMMENT '發布時間',
  `ANNOUNCE_TITLE` VARCHAR(40) NOT NULL COMMENT '公告標題',
  `ANNOUNCE_CONTEN` VARCHAR(1200) NOT NULL COMMENT '公告內容',
  PRIMARY KEY (`ANNOUNCE_ID`),
  CONSTRAINT `ADMIN_ID`
    FOREIGN KEY (`ADMIN_ID`)
    REFERENCES `CFA104G2`.`ADMINISTRATOR` (`ADMIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '系統公告';

/*3-5.建立首頁幻燈片*/    
CREATE TABLE `CFA104G2`.`HOME_SLIDESHOW` (
  `HSS_ID` INT NOT NULL AUTO_INCREMENT COMMENT '幻燈片編號',
  `ADMIN_ID` INT NOT NULL COMMENT '管理員編號',
  `HSS_IMG` BLOB NULL COMMENT '圖片',
  `HSS_TEXT` VARCHAR(80) NOT NULL COMMENT '圖片描述',
  `HSS_TIME` TIMESTAMP NOT NULL COMMENT '發布時間',
  `HSS_STATE` TINYINT(1) NOT NULL COMMENT '圖片狀態',
  `HSS_ON_SHELF` DATETIME NOT NULL COMMENT '上架時間',
  `HSS_OFF_SHELF` DATETIME NOT NULL COMMENT '下架時間',
  PRIMARY KEY (`HSS_ID`),
  FOREIGN KEY (`ADMIN_ID`)
  REFERENCES `CFA104G2`.`ADMINISTRATOR` (`ADMIN_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
COMMENT = '首頁幻燈片';


/****************************************/