/*認養區資料重刷*/
-- CREATE DATABASE IF NOT EXISTS `CFA104G2`;

use CFA104G2;

DROP TABLE IF EXISTS `PROJ_DISCUSSION`;
DROP TABLE IF EXISTS `PROJ_REPORT`;
DROP TABLE IF EXISTS `PROJ_ORDER`;
DROP TABLE IF EXISTS `PROJ_PERK`;
DROP TABLE IF EXISTS `PROJ_COLLECTION`;
DROP TABLE IF EXISTS `PROJ_DIARY_PIC`;
DROP TABLE IF EXISTS `PROJ_DIARY`;
DROP TABLE IF EXISTS `PROJ_PIC`;
DROP TABLE IF EXISTS `PROJECT`;
-- DROP TABLE IF EXISTS `F_MEM`;
-- DROP TABLE IF EXISTS `MEM`;


-- 暫時建立用來做FK
-- CREATE TABLE `CFA104G2`.`MEM` (
-- `MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT '一般會員編號',
-- PRIMARY KEY (`MEM_ID`));

--  暫時建立用來做FK
-- CREATE TABLE  `CFA104G2`.`F_MEM` (
-- `F_MEM_ID` INT NOT NULL AUTO_INCREMENT COMMENT'小農會員編號',
-- PRIMARY KEY (`F_MEM_ID`));

/*5-1.認養專案*/
CREATE TABLE `CFA104G2`.`PROJECT` (
  `PROJ_ID` int NOT NULL AUTO_INCREMENT,
  `F_MEM_ID` int NOT NULL,
  `PROJ_NAME` varchar(40) NOT NULL,
  `PROJ_STATE` tinyint(1) NOT NULL COMMENT '0: 專案待啟動\n1: 專案進行中\n2: 專案已結束',
  `PROJ_MAIN_PIC` LONGBLOB,
  `PROJ_ABSTRACT` varchar(300) NOT NULL,
  `PROJ_GOAL` int NOT NULL,
  `START_DATE` datetime(6) NOT NULL,
  `EXCEPTED_END_DATE` datetime(6) DEFAULT NULL,
  `ACTUAL_END_DATE` datetime(6) DEFAULT NULL,
  `PROJ_TOTAL_FUND` int NOT NULL,
  `PROJ_INTRO` varchar(500) NOT NULL,
  `PROJ_RISK` varchar(500) DEFAULT NULL,
  `PROJ_TOTAL_COUNT` int DEFAULT NULL,
  `PROJ_VIDEO` varchar(100) DEFAULT NULL COMMENT 'youtube文字聯結',
  `MEM_REPORT_COUNT` tinyint DEFAULT NULL,
  `PROJ_PAY` tinyint(1) DEFAULT NULL COMMENT '0:皆可以\n1:信用卡\n2:銀行轉帳',
  PRIMARY KEY (`PROJ_ID`),
  CONSTRAINT `FK_PROJECT_F_MEM_ID`
	FOREIGN KEY (`F_MEM_ID`)
	REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案';


/*5-2.認養專案照片*/
CREATE TABLE `CFA104G2`.`PROJ_PIC` (
  `PROJ_PIC_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `PROJ_PIC` LONGBLOB NULL,
  PRIMARY KEY (`PROJ_PIC_ID`),
  CONSTRAINT `FK_PROJ_DISCUSSION_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養日誌照片';


/*5-4.認養日誌*/
CREATE TABLE `CFA104G2`.`PROJ_DIARY` (
  `DIR_ID` INT NOT NULL AUTO_INCREMENT COMMENT '認養日誌編號',
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `DIR_UPLOAD_DATE` DATETIME NOT NULL COMMENT '日誌日期',
  `DIR_PROCEDURE` VARCHAR(20) NULL COMMENT '生產過程',
  `DIR_PRODUCT` VARCHAR(20) NULL COMMENT '產品/種苗',
  `DIR_EQUIPMENT` VARCHAR(40) NULL COMMENT '器具',
  `DIR_MATERIAL` VARCHAR(100) NULL COMMENT '資材',
  `DIR_EMOJI` VARCHAR(20) NULL COMMENT '心情',
  `DIR_NOTES` VARCHAR(200) NULL COMMENT '心得筆記',
  PRIMARY KEY (`DIR_ID`),
  INDEX `PROJ_ID_idx` (`PROJ_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_DIARY_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養日誌';


/*5-3.認養日誌照片*/
CREATE TABLE `CFA104G2`.`PROJ_DIARY_PIC` (
  `DIR_PIC_ID` INT NOT NULL AUTO_INCREMENT COMMENT '認養日誌照片編號',
  `DIR_ID` INT NOT NULL COMMENT '認養日誌編號',
  `DIR_PIC` LONGBLOB NULL COMMENT '認養日誌照片',
  PRIMARY KEY (`DIR_PIC_ID`),
  CONSTRAINT `FK_PROJ_DIARY_PIC_DIR_ID`
    FOREIGN KEY (`DIR_ID`)
    REFERENCES `CFA104G2`.`PROJ_DIARY` (`DIR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養日誌照片';


/*5-5.認養專案收藏列表*/
CREATE TABLE `CFA104G2`.`PROJ_COLLECTION` (
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `MEM_ID` INT NOT NULL COMMENT '一般會員編號',
  PRIMARY KEY (`PROJ_ID`, `MEM_ID`),
  INDEX `FK_PROJ_COLLECTION_MEM_ID_idx` (`MEM_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_COLLECTION_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_COLLECTION_MEM_ID`
    FOREIGN KEY (`MEM_ID`)
    REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養專案收藏列表';


/*5-6.認養回饋方案*/
CREATE TABLE `CFA104G2`.`PROJ_PERK` (
  `PERK_ID` INT NOT NULL AUTO_INCREMENT COMMENT '回饋方案編號',
  `PROJ_ID` INT NOT NULL COMMENT '認養專案編號',
  `PERK_PIC` LONGBLOB NULL COMMENT '方案插圖',
  `PERK_INTRO` VARCHAR(45) NOT NULL COMMENT '方案文字',
  `PERK_TOTAL_COUNT` INT NOT NULL COMMENT '方案總人數',
  `PERK_TOTAL_FUND` INT NOT NULL COMMENT '方案金額',
  `PERK_LIMITED` INT NULL COMMENT '限量',
  `PERK_SHIP_DATE` DATETIME NOT NULL COMMENT '預計寄送時間',
  `PERK_SHIP_AREA` VARCHAR(45) NOT NULL COMMENT '可寄送區域',
  PRIMARY KEY (`PERK_ID`),
  INDEX `FK_PROJ_PERK_PROJ_ID_idx` (`PROJ_ID` ASC) VISIBLE,
  CONSTRAINT `FK_PROJ_PERK_PROJ_ID`
    FOREIGN KEY (`PROJ_ID`)
    REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '認養回饋方案';


/*5-7.認養訂單*/
CREATE TABLE `CFA104G2`.`PROJ_ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `MEM_ID` INT NOT NULL,
  `PERK_ID` INT NOT NULL,
  `ORDER_TIME` DATETIME NOT NULL,
  `ORDER_ADDR` VARCHAR(40) NOT NULL,
  `ORDER_STATE` TINYINT(1) NOT NULL COMMENT '0 : 待付款\n1 : 待出貨\n2 : 待收貨\n3 : 訂單已完成\n4 : 訂單不成立',
  `ORDER_CANCEL_TIME` DATETIME NULL,
  PRIMARY KEY (`ORDER_ID`),
  CONSTRAINT `FK_PROJ_ORDER_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_ORDER_PERK_ID`
	FOREIGN KEY (`PERK_ID`)
	REFERENCES `CFA104G2`.`PROJ_PERK` (`PERK_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養訂單';


/*5-8.認養專案檢舉單*/
CREATE TABLE `CFA104G2`.`PROJ_REPORT` (
  `PROJ_REPORT_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `MEM_ID` INT NOT NULL,
  `REPORT_REASON` VARCHAR(300) NOT NULL,
  `REPORT_TIME` DATETIME NOT NULL,
  `REPORT_STATE` TINYINT(1) NOT NULL COMMENT '0: 未處理\n1: 檢舉通過\n2: 檢舉未通過',
  `REPORT_NOTE` VARCHAR(300) NULL,
  PRIMARY KEY (`PROJ_REPORT_ID`),
  CONSTRAINT `FK_PROJ_REPORT_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_REPORT_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案檢舉單';


/*5-9.認養專案留言*/
CREATE TABLE `CFA104G2`.`PROJ_DISCUSSION` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `PROJ_ID` INT NOT NULL,
  `DISCUSSION_ID` INT NOT NULL,
  `MEM_ID` INT NOT NULL,
  `F_MEM_ID` INT NOT NULL,
  `COMMENT_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  CONSTRAINT `FK_PROJECT_PROJ_ID`
	FOREIGN KEY (`PROJ_ID`)
	REFERENCES `CFA104G2`.`PROJECT` (`PROJ_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_DISCUSSION_ID`
	FOREIGN KEY (`DISCUSSION_ID`)
	REFERENCES `CFA104G2`.`PROJ_DISCUSSION` (`COMMENT_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_MEM_ID`
	FOREIGN KEY (`MEM_ID`)
	REFERENCES `CFA104G2`.`MEM` (`MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROJ_DISCUSSION_F_MEM_ID`
	FOREIGN KEY (`F_MEM_ID`)
	REFERENCES `CFA104G2`.`F_MEM` (`F_MEM_ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION)
COMMENT = '認養專案留言';